import fs from "node:fs/promises";
import path from "node:path";
import {
  HERO_OUTFIT_PUBLIC_BASE,
  type OutfitFrameRole,
} from "@/lib/tr/outfitFrame/types";

const HERO_ROLES = ["top", "bottom"] as const satisfies readonly OutfitFrameRole[];

function projectRoot(): string {
  return process.cwd();
}

export function heroRolePublicDir(role: "top" | "bottom"): string {
  return path.join(projectRoot(), "public", "images", "tr", "hero", role);
}

export function heroSlotPiecesDataPath(): string {
  return path.join(projectRoot(), "src", "data", "tr", "heroSlotPieces.ts");
}

export function slugifyHeroFilename(name: string): string {
  const base = path.parse(name).name;
  return (
    base
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 80) || "piece"
  );
}

async function listPngs(dir: string): Promise<string[]> {
  try {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    return entries
      .filter((e) => e.isFile() && e.name.toLowerCase().endsWith(".png"))
      .map((e) => e.name)
      .sort((a, b) => a.localeCompare(b));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw error;
  }
}

export async function listHeroSlotPublicPaths(): Promise<{
  tops: string[];
  bottoms: string[];
}> {
  const [topFiles, bottomFiles] = await Promise.all([
    listPngs(heroRolePublicDir("top")),
    listPngs(heroRolePublicDir("bottom")),
  ]);

  return {
    tops: topFiles.map((f) => `${HERO_OUTFIT_PUBLIC_BASE}/top/${f}`),
    bottoms: bottomFiles.map((f) => `${HERO_OUTFIT_PUBLIC_BASE}/bottom/${f}`),
  };
}

function renderHeroSlotPiecesFile(tops: string[], bottoms: string[]): string {
  const fmt = (paths: string[]) =>
    paths.length === 0
      ? "[]"
      : `[\n${paths.map((src) => `  { src: "${src}" },`).join("\n")}\n]`;

  return `/**
 * Curated cutouts for the /tr hero slot mixer.
 * Regenerated by \`npm run tr:import-hero\` or the local /tr/dev/hero-import panel.
 * Do not hand-edit paths — re-import after changing assets.
 */

export type HeroSlotPiece = {
  src: string;
};

export const HERO_SLOT_TOPS: readonly HeroSlotPiece[] = ${fmt(tops)};

export const HERO_SLOT_BOTTOMS: readonly HeroSlotPiece[] = ${fmt(bottoms)};
`;
}

/** Scan public hero folders and rewrite heroSlotPieces.ts. */
export async function rewriteHeroSlotPiecesFromDisk(): Promise<{
  tops: string[];
  bottoms: string[];
}> {
  const lists = await listHeroSlotPublicPaths();
  await fs.writeFile(
    heroSlotPiecesDataPath(),
    renderHeroSlotPiecesFile(lists.tops, lists.bottoms),
    "utf8",
  );
  return lists;
}

export async function writeNormalizedHeroSlot(params: {
  role: "top" | "bottom";
  filenameHint: string;
  png: Buffer;
}): Promise<{ src: string; filename: string }> {
  const dir = heroRolePublicDir(params.role);
  await fs.mkdir(dir, { recursive: true });

  const existing = new Set(await listPngs(dir));
  let slug = slugifyHeroFilename(params.filenameHint);
  let filename = `${slug}.png`;
  let n = 2;
  while (existing.has(filename)) {
    filename = `${slug}-${n}.png`;
    n += 1;
  }

  await fs.writeFile(path.join(dir, filename), params.png);
  const lists = await rewriteHeroSlotPiecesFromDisk();
  const src =
    params.role === "top"
      ? lists.tops.find((p) => p.endsWith(`/${filename}`))
      : lists.bottoms.find((p) => p.endsWith(`/${filename}`));

  return {
    src: src ?? `${HERO_OUTFIT_PUBLIC_BASE}/${params.role}/${filename}`,
    filename,
  };
}

export async function deleteHeroSlotFile(params: {
  role: "top" | "bottom";
  filename: string;
}): Promise<void> {
  const safe = path.basename(params.filename);
  if (!safe.toLowerCase().endsWith(".png") || safe !== params.filename) {
    throw new Error("Invalid filename.");
  }
  const full = path.join(heroRolePublicDir(params.role), safe);
  await fs.unlink(full);
  await rewriteHeroSlotPiecesFromDisk();
}

export { HERO_ROLES };
