/**
 * Curated cutouts for the /tr hero slot mixer.
 * Regenerated by `npm run tr:import-hero` or the local /tr/dev/hero-import panel.
 * Do not hand-edit paths — re-import after changing assets.
 */

export type HeroSlotPiece = {
  src: string;
};

export const HERO_SLOT_TOPS: readonly HeroSlotPiece[] = [
  { src: "/images/tr/hero/top/a17c41be-1083-414a-bf6a-89c19e481d87-size1040x1386-cropcenter.png" },
  { src: "/images/tr/hero/top/c7193dbdeab63362ecf8dd7757076858.png" },
  { src: "/images/tr/hero/top/fender-alice-in-wonderland-177521323849889.png" },
];

export const HERO_SLOT_BOTTOMS: readonly HeroSlotPiece[] = [
  { src: "/images/tr/hero/bottom/1-a8eda633-22d3-45c4-8b63-4785c801a8ea.png" },
  { src: "/images/tr/hero/bottom/3db5f53e36f058679cf0c4a3a35a362c.png" },
  { src: "/images/tr/hero/bottom/7ae0b876da4b2823146aa38142bc9e10.png" },
  { src: "/images/tr/hero/bottom/ec4c76766d6af90f2d9ae2227b8765c0.png" },
];
