import { promises as fs } from "fs";
import path from "path";
import type { CanvasItemLayout } from "@/types/canvas-layout";
import { stripLegacyModelLayers } from "@/lib/canvasLayout";

export const runtime = "nodejs";

const LOOK_ID_PATTERN = /^look-[a-z0-9-]+$/;
const LAYOUTS_DIR = path.join(process.cwd(), "src/data/canvas-layouts");

interface SaveCanvasLayoutPayload {
  lookId?: string;
  layouts?: Record<string, CanvasItemLayout>;
}

function isDevRequest(request: Request): boolean {
  if (process.env.NODE_ENV !== "development") return false;

  const host =
    request.headers.get("x-forwarded-host") ??
    request.headers.get("host") ??
    "";

  return host.startsWith("localhost") || host.startsWith("127.0.0.1");
}

function toImportVarName(lookId: string): string {
  return lookId.replace(/-/g, "_");
}

async function regenerateCanvasLayoutIndex(): Promise<void> {
  const entries = await fs.readdir(LAYOUTS_DIR, { withFileTypes: true });
  const jsonFiles = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
    .map((entry) => entry.name)
    .sort();

  const imports = jsonFiles
    .map((fileName) => {
      const lookId = fileName.replace(/\.json$/, "");
      return `import ${toImportVarName(lookId)} from "./${fileName}";`;
    })
    .join("\n");

  const mapEntries = jsonFiles
    .map((fileName) => {
      const lookId = fileName.replace(/\.json$/, "");
      return `  "${lookId}": ${toImportVarName(lookId)},`;
    })
    .join("\n");

  const content = `// Auto-generated by POST /api/save-canvas-layout — do not edit manually.
${imports ? `${imports}\n` : ""}import type { CanvasItemLayout } from "@/types/canvas-layout";

export const committedCanvasLayouts: Record<
  string,
  Record<string, CanvasItemLayout>
> = {
${mapEntries}
};
`;

  await fs.writeFile(path.join(LAYOUTS_DIR, "index.ts"), content, "utf8");
}

export async function POST(request: Request) {
  if (!isDevRequest(request)) {
    return Response.json(
      { error: "Canvas layout sync is only available in local development." },
      { status: 403 },
    );
  }

  let payload: SaveCanvasLayoutPayload;

  try {
    payload = (await request.json()) as SaveCanvasLayoutPayload;
  } catch {
    return Response.json({ error: "Invalid JSON payload." }, { status: 400 });
  }

  const lookId = payload.lookId?.trim();
  const layouts = payload.layouts;

  if (!lookId || !LOOK_ID_PATTERN.test(lookId)) {
    return Response.json(
      { error: 'A valid lookId is required (e.g. "look-01").' },
      { status: 400 },
    );
  }

  if (!layouts || typeof layouts !== "object" || Array.isArray(layouts)) {
    return Response.json(
      { error: "layouts must be an object keyed by canvas item id." },
      { status: 400 },
    );
  }

  await fs.mkdir(LAYOUTS_DIR, { recursive: true });

  const cleanedLayouts = stripLegacyModelLayers(layouts);
  const filePath = path.join(LAYOUTS_DIR, `${lookId}.json`);
  await fs.writeFile(
    filePath,
    `${JSON.stringify(cleanedLayouts, null, 2)}\n`,
    "utf8",
  );
  await regenerateCanvasLayoutIndex();

  return Response.json({
    ok: true,
    lookId,
    file: `src/data/canvas-layouts/${lookId}.json`,
  });
}
