// Auto-generated by POST /api/save-canvas-layout — do not edit manually.
import look_01 from "./look-01.json";
import type { CanvasItemLayout } from "@/lib/canvasLayout";

export const committedCanvasLayouts: Record<
  string,
  Record<string, CanvasItemLayout>
> = {
  "look-01": look_01,
};
